// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNql_Eq6etB7pXiT15TGu9aTrvGBcnTg',
    appId: '1:983572307887:web:235a3aaef978e324da995a',
    messagingSenderId: '983572307887',
    projectId: 'test1-525a6',
    authDomain: 'test1-525a6.firebaseapp.com',
    databaseURL: 'https://test1-525a6-default-rtdb.firebaseio.com',
    storageBucket: 'test1-525a6.appspot.com',
    measurementId: 'G-3TNJJ5MYEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsjDeExFNYX_p6WtAe3ck08XDg1ZMBrw',
    appId: '1:983572307887:android:f5cc184ad5a0b51eda995a',
    messagingSenderId: '983572307887',
    projectId: 'test1-525a6',
    databaseURL: 'https://test1-525a6-default-rtdb.firebaseio.com',
    storageBucket: 'test1-525a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhYdyeN5xpMBorOMdQnUPCZIVP8YByNI',
    appId: '1:983572307887:ios:3dad6d090278a968da995a',
    messagingSenderId: '983572307887',
    projectId: 'test1-525a6',
    databaseURL: 'https://test1-525a6-default-rtdb.firebaseio.com',
    storageBucket: 'test1-525a6.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhYdyeN5xpMBorOMdQnUPCZIVP8YByNI',
    appId: '1:983572307887:ios:be850ad8af8187bdda995a',
    messagingSenderId: '983572307887',
    projectId: 'test1-525a6',
    databaseURL: 'https://test1-525a6-default-rtdb.firebaseio.com',
    storageBucket: 'test1-525a6.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
